"""add_card_steps_and_tip_to_raw_recipes

Adds card_steps (JSON text, 5-6 detailed cooking steps) and card_tip
(plain text, chef's tip) columns to raw_recipes. Generated by Claude
Haiku from raw_content on first card render and cached here.

Revision ID: j0k1l2m3n4o5
Revises: i9j0k1l2m3n4
Create Date: 2026-04-21
"""
from alembic import op
import sqlalchemy as sa

revision = "j0k1l2m3n4o5"
down_revision = "i9j0k1l2m3n4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("raw_recipes", sa.Column("card_steps", sa.Text(), nullable=True))
    op.add_column("raw_recipes", sa.Column("card_tip",   sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("raw_recipes", "card_tip")
    op.drop_column("raw_recipes", "card_steps")
